# Generated by Django 6.0.6 on 2026-06-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_question_answer_test_question_test_testresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='for_whom',
            field=models.TextField(blank=True, verbose_name='Кому подойдёт'),
        ),
        migrations.AddField(
            model_name='course',
            name='how_it_works',
            field=models.TextField(blank=True, verbose_name='Как проходит обучение'),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_learn',
            field=models.TextField(blank=True, verbose_name='Чему научитесь'),
        ),
    ]
