# Generated by Django 6.0.6 on 2026-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_for_whom_course_how_it_works_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('bio', models.TextField(verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, upload_to='teacher/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Профиль преподавателя',
                'verbose_name_plural': 'Профиль преподавателя',
            },
        ),
    ]
