# Generated by Django 6.0.6 on 2026-07-01 07:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_faq_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео (VK/YouTube)'),
        ),
    ]
