# Generated by Django 6.0.6 on 2026-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Адрес страницы'),
        ),
    ]
