# Generated by Django 6.0.6 on 2026-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_course_options_course_is_published_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Число')),
                ('label', models.CharField(max_length=100, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Цифра-достижение',
                'verbose_name_plural': 'Цифры-достижения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✦', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок "Почему мы"',
                'verbose_name_plural': 'Блоки "Почему мы"',
                'ordering': ['order'],
            },
        ),
    ]
