# Generated by Django 6.0.6 on 2026-07-02 09:31

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_statblock_whyusblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Текст задания')),
                ('submission_type', models.CharField(choices=[('text', 'Только текст'), ('file', 'Только файл'), ('both', 'Текст и файл')], default='text', max_length=10, verbose_name='Формат сдачи')),
                ('grading_type', models.CharField(choices=[('score', 'Баллы (0-100)'), ('pass_fail', 'Зачёт / незачёт'), ('comment_only', 'Только комментарий')], default='pass_fail', max_length=15, verbose_name='Формат оценки')),
                ('allow_resubmit', models.BooleanField(default=True, verbose_name='Разрешить пересдачу')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='school.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('checked', 'Проверено')], default='pending', max_length=10, verbose_name='Статус')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Баллы')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Зачёт')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.homework', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Сдача домашнего задания',
                'verbose_name_plural': 'Сдачи домашних заданий',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
