# Generated by Django 6.0.6 on 2026-07-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_module_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
