# Generated by Django 6.0.6 on 2026-07-04 11:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_enrollment_approved_at_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='conspect',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Конспект (PDF)'),
        ),
    ]
