# Generated by Django 6.0.6 on 2026-07-05 11:17

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_lesson_conspect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Задание')),
                ('checkpoint_type', models.CharField(choices=[('auto', 'Автопроверка текста'), ('manual', 'Проверка преподавателем')], default='manual', max_length=10, verbose_name='Тип проверки')),
                ('correct_answers', models.TextField(blank=True, verbose_name='Правильные ответы (по одному на строку)')),
                ('submission_type', models.CharField(choices=[('text', 'Только текст'), ('file', 'Только файл'), ('both', 'Текст и файл')], default='text', max_length=10, verbose_name='Формат сдачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок среди точек в этом месте')),
                ('after_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='school.module', verbose_name='После раздела (пусто = в начале курса)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='school.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Контрольная точка',
                'verbose_name_plural': 'Контрольные точки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('checked', 'Проверено')], default='pending', max_length=10, verbose_name='Статус')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Зачтено')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.checkpoint', verbose_name='Точка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Сдача контрольной точки',
                'verbose_name_plural': 'Сдачи контрольных точек',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
