# Generated by Django 6.0.6 on 2026-07-05 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_checkpoint_checkpointsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpointsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Сдача задания контрольной точки', 'verbose_name_plural': 'Сдачи заданий контрольных точек'},
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='checkpoint_type',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='submission_type',
        ),
        migrations.RemoveField(
            model_name='checkpointsubmission',
            name='checkpoint',
        ),
        migrations.CreateModel(
            name='CheckpointTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Задание')),
                ('task_type', models.CharField(choices=[('auto', 'Автопроверка текста'), ('manual', 'Проверка преподавателем')], default='manual', max_length=10, verbose_name='Тип проверки')),
                ('correct_answers', models.TextField(blank=True, verbose_name='Правильные ответы (по одному на строку)')),
                ('submission_type', models.CharField(choices=[('text', 'Только текст'), ('file', 'Только файл'), ('both', 'Текст и файл')], default='text', max_length=10, verbose_name='Формат сдачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.checkpoint', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Задание контрольной точки',
                'verbose_name_plural': 'Задания контрольной точки',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='checkpointsubmission',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='school.checkpointtask', verbose_name='Задание'),
            preserve_default=False,
        ),
    ]
