# Generated by Django 6.0.6 on 2026-07-07 10:10

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_checkpointsubmission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckpointAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='school.checkpoint', verbose_name='Точка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Попытка контрольной точки',
                'verbose_name_plural': 'Попытки контрольных точек',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('checked', 'Проверено')], default='pending', max_length=10, verbose_name='Статус')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Зачтено')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='school.checkpointtask', verbose_name='Задание')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='school.checkpointattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Ответ на задание точки',
                'verbose_name_plural': 'Ответы на задания точки',
            },
        ),
        migrations.DeleteModel(
            name='CheckpointSubmission',
        ),
    ]
