# Generated by Django 6.0.6 on 2026-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointtask',
            name='submission_type',
            field=models.CharField(choices=[('text', 'Только текст'), ('file', 'Только файл'), ('both', 'Текст или файл (на выбор)')], default='text', max_length=10, verbose_name='Формат сдачи'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='submission_type',
            field=models.CharField(choices=[('text', 'Только текст'), ('file', 'Только файл'), ('both', 'Текст или файл (на выбор)')], default='text', max_length=10, verbose_name='Формат сдачи'),
        ),
    ]
