# Generated by Django 6.0.6 on 2026-07-08 10:19

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_checkpointtask_submission_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Время на выполнение (минут)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='school.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Пробник ЕГЭ',
                'verbose_name_plural': 'Пробники ЕГЭ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False, verbose_name='Отправлено автоматически по таймеру')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='school.exammock', verbose_name='Пробник')),
            ],
            options={
                'verbose_name': 'Попытка пробника',
                'verbose_name_plural': 'Попытки пробника',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Задание')),
                ('task_type', models.CharField(choices=[('auto', 'Автопроверка текста'), ('manual', 'Проверка преподавателем')], default='manual', max_length=10, verbose_name='Тип проверки')),
                ('correct_answers', models.TextField(blank=True, verbose_name='Правильные ответы (по одному на строку)')),
                ('submission_type', models.CharField(choices=[('text', 'Только текст'), ('file', 'Только файл'), ('either', 'Текст или файл (на выбор)')], default='text', max_length=10, verbose_name='Формат сдачи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.exammock', verbose_name='Пробник')),
            ],
            options={
                'verbose_name': 'Задание пробника',
                'verbose_name_plural': 'Задания пробника',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('checked', 'Проверено')], default='pending', max_length=10, verbose_name='Статус')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Зачтено')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='school.examattempt', verbose_name='Попытка')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='school.examtask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Ответ на задание пробника',
                'verbose_name_plural': 'Ответы на задания пробника',
            },
        ),
    ]
