# Generated by Django 6.0.6 on 2026-07-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_exammock_examattempt_examtask_examanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FearBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Страх (вопрос в кавычках)')),
                ('answer', models.TextField(verbose_name='Ответ (можно с <b>жирным</b>)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок «Страхи»',
                'verbose_name_plural': 'Блоки «Страхи»',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✓', max_length=10, verbose_name='Эмодзи')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Блок «Родителям»',
                'verbose_name_plural': 'Блоки «Родителям»',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='егэ и огэ по русскому — без паники', max_length=200, verbose_name='Надпись над заголовком (рукописная)')),
                ('hero_title', models.CharField(default='сдай русский на максимум с личным преподавателем', max_length=300, verbose_name='Главный заголовок')),
                ('hero_subtitle', models.TextField(blank=True, default='', verbose_name='Подзаголовок')),
                ('grade_number', models.CharField(default='100', max_length=10, verbose_name='Число в кружке на фото')),
                ('grade_label', models.CharField(default='ЕГЭ', max_length=20, verbose_name='Подпись в кружке')),
            ],
            options={
                'verbose_name': 'Настройки главной',
                'verbose_name_plural': 'Настройки главной',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='card_features',
            field=models.TextField(blank=True, verbose_name='Пункты на карточке (по одному на строку)'),
        ),
        migrations.AddField(
            model_name='course',
            name='card_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тег на карточке (например «9 класс»)'),
        ),
    ]
