# Generated by Django 6.0.6 on 2026-07-19 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_alter_teacherprofile_options_course_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Объяснение (показывается при ошибке)'),
        ),
        migrations.CreateModel(
            name='TestAnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('chosen_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.answer', verbose_name='Выбранный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.question', verbose_name='Вопрос')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='school.testresult', verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Ответ в тесте',
                'verbose_name_plural': 'Ответы в тестах',
            },
        ),
    ]
