# Generated by Django 6.0.6 on 2026-07-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_question_explanation_testanswerlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='review',
            name='score_after',
            field=models.CharField(blank=True, max_length=10, verbose_name='Балл «стало»'),
        ),
        migrations.AddField(
            model_name='review',
            name='score_before',
            field=models.CharField(blank=True, max_length=10, verbose_name='Балл «было»'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_screenshot',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Скриншот личного кабинета'),
        ),
    ]
