# Generated by Django 6.0.6 on 2026-07-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_review_city_review_score_after_review_score_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statblock',
            name='icon',
            field=models.CharField(default='⭐', max_length=10, verbose_name='Эмодзи'),
        ),
    ]
