# Generated by Django 6.0.6 on 2026-07-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_alter_review_options_remove_review_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_seconds', models.PositiveIntegerField(verbose_name='Время (в секундах)')),
                ('label', models.CharField(max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timecodes', to='school.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Таймкод',
                'verbose_name_plural': 'Таймкоды',
                'ordering': ['time_seconds'],
            },
        ),
    ]
