# Generated by Django 6.0.6 on 2026-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_timecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentblock',
            name='icon',
            field=models.CharField(default='✓', max_length=30, verbose_name='Эмодзи'),
        ),
        migrations.AlterField(
            model_name='statblock',
            name='icon',
            field=models.CharField(default='⭐', max_length=30, verbose_name='Эмодзи'),
        ),
        migrations.AlterField(
            model_name='whyusblock',
            name='icon',
            field=models.CharField(default='✦', max_length=30, verbose_name='Иконка (эмодзи)'),
        ),
    ]
