# Generated by Django 6.0.6 on 2026-07-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_alter_parentblock_icon_alter_statblock_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_bio_override',
            field=models.TextField(blank=True, verbose_name='Подпись/био преподавателя для этого курса (если отличается)'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_photo_override',
            field=models.ImageField(blank=True, upload_to='course_teacher/', verbose_name='Фото преподавателя для этого курса (если отличается)'),
        ),
    ]
