# Generated by Django 6.0.6 on 2026-07-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_course_teacher_bio_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher_bio_override',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_photo_override',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Короткая фраза или имя'),
        ),
        migrations.CreateModel(
            name='CourseTeacherDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_override', models.CharField(blank=True, max_length=200, verbose_name='Другая короткая фраза/имя для этого курса')),
                ('photo_override', models.ImageField(blank=True, upload_to='course_teacher/', verbose_name='Другое фото для этого курса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_displays', to='school.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_displays', to='school.teacherprofile', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Преподаватель на странице курса',
                'verbose_name_plural': 'Преподаватели на странице курса',
                'ordering': ['order'],
                'unique_together': {('course', 'teacher')},
            },
        ),
    ]
