# Generated by Django 6.0.6 on 2026-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_remove_course_teacher_bio_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteacherdisplay',
            name='bio_override',
            field=models.TextField(blank=True, verbose_name='Другой текст/описание для этого курса'),
        ),
    ]
