# Generated by Django 6.0.6 on 2026-07-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_courseteacherdisplay_bio_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('ege', 'ЕГЭ'), ('oge', 'ОГЭ')], max_length=10, verbose_name='Тип экзамена'),
        ),
    ]
