# Generated by Django 6.0.6 on 2026-07-24 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_teacherprofile_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Пункт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_items', to='school.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Пункт «Кому подойдёт»',
                'verbose_name_plural': 'Пункты «Кому подойдёт»',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Пункт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='school.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Пункт «Что получит ученик»',
                'verbose_name_plural': 'Пункты «Что получит ученик»',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Пункт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='school.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Шаг «Как проходит обучение»',
                'verbose_name_plural': 'Шаги «Как проходит обучение»',
                'ordering': ['order'],
            },
        ),
    ]
