# Generated by Django 6.0.6 on 2026-07-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_migrate_course_text_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='for_whom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='how_it_works',
        ),
        migrations.RemoveField(
            model_name='course',
            name='what_you_learn',
        ),
        migrations.AddField(
            model_name='courseaudience',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='coursebenefit',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='coursestep',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='courseaudience',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coursebenefit',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coursestep',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
    ]
