# Generated by Django 6.0.6 on 2026-07-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_remove_course_for_whom_remove_course_how_it_works_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseaudience',
            name='icon',
            field=models.CharField(default='target', max_length=30, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='coursebenefit',
            name='icon',
            field=models.CharField(default='check-circle', max_length=30, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='coursestep',
            name='icon',
            field=models.CharField(default='play-circle', max_length=30, verbose_name='Иконка'),
        ),
    ]
