# Generated by Django 6.0.6 on 2026-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_courseaudience_icon_coursebenefit_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('ege', 'ЕГЭ'), ('oge', 'ОГЭ')], max_length=10, verbose_name='Тип экзамена'),
        ),
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Предмет'),
        ),
    ]
