# Generated by Django 6.0.6 on 2026-07-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_review_exam_type_review_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nav_short_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Короткое название для меню (например «Профильная», «Базовая»)'),
        ),
    ]
