# Generated by Django 6.0.6 on 2026-07-27 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_course_nav_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointattempt',
            name='earned_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы'),
        ),
        migrations.AddField(
            model_name='checkpointattempt',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы'),
        ),
        migrations.AddField(
            model_name='checkpointtask',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный первичный балл'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='earned_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы'),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='earned_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы'),
        ),
        migrations.AddField(
            model_name='examtask',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный первичный балл'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='earned_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы'),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальный первичный балл'),
        ),
        migrations.AddField(
            model_name='testanswerlog',
            name='earned_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы'),
        ),
        migrations.AddField(
            model_name='testanswerlog',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='data_quality',
            field=models.CharField(choices=[('exact', 'Точные данные'), ('estimated', 'Оценочные данные'), ('legacy', 'Устаревшие данные')], default='legacy', max_length=10, verbose_name='Качество данных'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='earned_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы'),
        ),
    ]
