# Generated by Django 6.0.6 on 2026-07-28 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_analytics_points_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='data_quality',
        ),
        migrations.AddField(
            model_name='checkpointanswer',
            name='earned_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы'),
        ),
        migrations.AddField(
            model_name='checkpointanswer',
            name='max_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы'),
        ),
        migrations.AddField(
            model_name='checkpointattempt',
            name='analytics_data_quality',
            field=models.CharField(choices=[('exact', 'Точные данные'), ('reconstructed', 'Восстановленные данные'), ('estimated', 'Приблизительные данные'), ('legacy', 'Недостаточно данных')], db_index=True, default='legacy', max_length=15, verbose_name='Качество аналитических данных'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='analytics_data_quality',
            field=models.CharField(choices=[('exact', 'Точные данные'), ('reconstructed', 'Восстановленные данные'), ('estimated', 'Приблизительные данные'), ('legacy', 'Недостаточно данных')], db_index=True, default='legacy', max_length=15, verbose_name='Качество аналитических данных'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='analytics_data_quality',
            field=models.CharField(choices=[('exact', 'Точные данные'), ('reconstructed', 'Восстановленные данные'), ('estimated', 'Приблизительные данные'), ('legacy', 'Недостаточно данных')], db_index=True, default='legacy', max_length=15, verbose_name='Качество аналитических данных'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='analytics_data_quality',
            field=models.CharField(choices=[('exact', 'Точные данные'), ('reconstructed', 'Восстановленные данные'), ('estimated', 'Приблизительные данные'), ('legacy', 'Недостаточно данных')], db_index=True, default='legacy', max_length=15, verbose_name='Качество аналитических данных'),
        ),
    ]
