# Generated by Django 6.0.6 on 2026-07-28 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_analytics_quality_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год экзамена')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('available_days_per_week', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Доступных дней в неделю')),
                ('daily_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Минут в день')),
                ('onboarding_completed', models.BooleanField(default=False, verbose_name='Онбординг пройден')),
                ('diagnostic_completed', models.BooleanField(default=False, verbose_name='Диагностика пройдена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль ученика',
                'verbose_name_plural': 'Профили учеников',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='school.subject', verbose_name='Предмет (нормализованный)'),
        ),
        migrations.AddField(
            model_name='review',
            name='subject_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='school.subject', verbose_name='Предмет (нормализованный)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subject_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='school.subject', verbose_name='Предмет (нормализованный)'),
        ),
        migrations.CreateModel(
            name='StudentSubjectGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_test_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Целевой тестовый балл')),
                ('exam_year', models.PositiveSmallIntegerField(verbose_name='Год экзамена')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='Дата экзамена')),
                ('weekly_minutes', models.PositiveSmallIntegerField(default=300, verbose_name='Минут в неделю на предмет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='school.studentprofile', verbose_name='Ученик')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_goals', to='school.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Цель по предмету',
                'verbose_name_plural': 'Цели по предметам',
                'ordering': ['subject__order', 'subject__name'],
                'indexes': [models.Index(fields=['student', 'is_active'], name='school_stud_student_9b7f15_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'exam_year'), name='unique_goal_per_subject_year')],
            },
        ),
        migrations.CreateModel(
            name='ScoreConversionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('ege', 'ЕГЭ'), ('oge', 'ОГЭ')], max_length=10, verbose_name='Тип экзамена')),
                ('exam_year', models.PositiveSmallIntegerField(verbose_name='Год экзамена')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Версия')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Источник / комментарий')),
                ('table', models.JSONField(default=dict, help_text='Ключ — первичный балл, значение — тестовый: {"0": 0, "1": 3, ...}', verbose_name='Таблица перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversion_tables', to='school.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Шкала перевода баллов',
                'verbose_name_plural': 'Шкалы перевода баллов',
                'ordering': ['-exam_year', 'subject__name', '-version'],
                'indexes': [models.Index(fields=['subject', 'exam_year', 'is_active'], name='school_scor_subject_e34b79_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject', 'exam_type', 'exam_year', 'version'), name='unique_conversion_version'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('subject', 'exam_type', 'exam_year'), name='single_active_conversion_table')],
            },
        ),
    ]
