# Generated by Django 6.0.6 on 2026-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_subjects_profiles_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreconversiontable',
            name='table',
            field=models.JSONField(blank=True, default=dict, help_text='Ключ — первичный балл, значение — тестовый: {"0": 0, "1": 3, ...}', verbose_name='Таблица перевода'),
        ),
    ]
