# Generated by Django 6.0.6 on 2026-07-28 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school', '0045_backfill_primary_scores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(choices=[('theory', 'Не знаю теорию'), ('misread', 'Неверно понял условие'), ('calculation', 'Ошибка в вычислениях'), ('careless', 'Невнимательность'), ('strategy', 'Неправильная стратегия'), ('formatting', 'Ошибка оформления'), ('random', 'Случайный ответ'), ('unclassified', 'Не классифицирована')], default='unclassified', max_length=20, verbose_name='Тип ошибки')),
                ('status', models.CharField(choices=[('not_analyzed', 'Не разобрано'), ('in_progress', 'В работе'), ('corrected_once', 'Исправлено один раз'), ('reinforced', 'Закреплено'), ('regressed', 'Вернулось в ошибки')], db_index=True, default='not_analyzed', max_length=20, verbose_name='Статус')),
                ('repeated_count', models.PositiveSmallIntegerField(default=1, verbose_name='Сколько раз повторилась')),
                ('explanation_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Объяснение изучено')),
                ('first_detected_at', models.DateTimeField(auto_now_add=True)),
                ('last_detected_at', models.DateTimeField(auto_now=True)),
                ('reinforced_at', models.DateTimeField(blank=True, null=True, verbose_name='Закреплено')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_records', to='school.lesson', verbose_name='Урок')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_records', to='school.question', verbose_name='Вопрос теста')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Тип источника')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_records', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_records', to='school.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Ошибка ученика',
                'verbose_name_plural': 'Ошибки учеников',
                'ordering': ['-last_detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorCorrectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(default=False, verbose_name='Решено верно')),
                ('is_similar_task', models.BooleanField(default=True, verbose_name='Аналогичное задание')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Ключ учебной сессии')),
                ('error_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_attempts', to='school.errorrecord', verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Попытка исправления ошибки',
                'verbose_name_plural': 'Попытки исправления ошибок',
                'ordering': ['attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('archived', 'В архиве')], default='active', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('system', 'Система'), ('teacher', 'Преподаватель'), ('student', 'Ученик')], default='system', max_length=20, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_plans', to='school.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('lesson', 'Урок'), ('mini_check', 'Мини-проверка'), ('practice', 'Практика'), ('homework', 'Домашняя работа'), ('mock_exam', 'Пробник'), ('review', 'Повторение'), ('error_work', 'Работа над ошибками')], max_length=30, verbose_name='Тип задачи')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('due_at', models.DateTimeField(verbose_name='Срок')),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='Оценка времени, мин')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательная')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('in_progress', 'В процессе'), ('done_on_time', 'Выполнено вовремя'), ('done_late', 'Выполнено с опозданием'), ('overdue', 'Просрочено'), ('cancelled_by_teacher', 'Отменено преподавателем'), ('cancelled_by_system', 'Отменено системой'), ('skipped', 'Пропущено учеником')], db_index=True, default='planned', max_length=25, verbose_name='Статус')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=300, verbose_name='Причина отмены')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.PositiveSmallIntegerField(default=5, verbose_name='Приоритет (1 — высший)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='school.studyplan', verbose_name='План')),
            ],
            options={
                'verbose_name': 'Задача плана',
                'verbose_name_plural': 'Задачи плана',
                'ordering': ['due_at', 'priority', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, max_length=30, verbose_name='Тип активности')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('client_session_id', models.CharField(max_length=64, verbose_name='ID сессии клиента')),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('active_seconds', models.PositiveIntegerField(default=0, verbose_name='Активных секунд')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='school.course', verbose_name='Курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Учебная сессия',
                'verbose_name_plural': 'Учебные сессии',
                'ordering': ['-start_at'],
            },
        ),
        migrations.AddIndex(
            model_name='errorrecord',
            index=models.Index(fields=['student', 'status'], name='school_erro_student_634cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='errorrecord',
            index=models.Index(fields=['student', 'question'], name='school_erro_student_ccbb21_idx'),
        ),
        migrations.AddIndex(
            model_name='errorrecord',
            index=models.Index(fields=['student', 'subject'], name='school_erro_student_843bec_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['student', 'status'], name='school_stud_student_10277b_idx'),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['status', 'due_at'], name='school_plan_status_3d0f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['plan', 'status'], name='school_plan_plan_id_a57f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['student', 'start_at'], name='school_stud_student_715b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['student', 'ended_at'], name='school_stud_student_032063_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(fields=('student', 'client_session_id'), name='unique_client_session_per_student'),
        ),
    ]
