# Generated by Django 6.0.6 on 2026-07-29 20:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_errors_sessions_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 — не показывать', verbose_name='Длительность, мин'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='learning_goal',
            field=models.TextField(blank=True, help_text='Что ученик будет уметь после урока. Одно-два предложения.', verbose_name='Учебная цель'),
        ),
        migrations.CreateModel(
            name='LessonViewProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds', models.PositiveIntegerField(default=0, verbose_name='Последняя позиция, сек')),
                ('watched_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Просмотрено, %')),
                ('marked_manually', models.BooleanField(default=False, verbose_name='Отмечен вручную')),
                ('returns_count', models.PositiveSmallIntegerField(default=0, verbose_name='Возвращений к уроку')),
                ('first_opened_at', models.DateTimeField(auto_now_add=True)),
                ('last_opened_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_progress', to='school.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_views', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Просмотр урока',
                'verbose_name_plural': 'Просмотры уроков',
                'indexes': [models.Index(fields=['student', 'lesson'], name='school_less_student_2602e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_lesson_view')],
            },
        ),
    ]
