# Generated by Django 6.0.6 on 2026-07-30 10:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_lesson_goal_and_view_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('single', 'Один вариант'), ('multiple', 'Несколько вариантов'), ('text', 'Короткий ответ')], default='single', max_length=10, verbose_name='Тип ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text',
            field=models.CharField(blank=True, help_text='Несколько допустимых вариантов — через точку с запятой', max_length=300, verbose_name='Правильный ответ (для короткого ответа)'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam_task_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер задания ЕГЭ'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_in_bank',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В банке заданий'),
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='school.lesson', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='school.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы')),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы')),
                ('analytics_data_quality', models.CharField(choices=[('exact', 'Точные данные'), ('reconstructed', 'Восстановленные данные'), ('estimated', 'Приблизительные данные'), ('legacy', 'Недостаточно данных')], db_index=True, default='legacy', max_length=15, verbose_name='Качество аналитических данных')),
                ('mode', models.CharField(choices=[('topic', 'По теме'), ('exam_number', 'По номеру задания'), ('weak', 'По слабым местам'), ('errors', 'По ошибкам'), ('mixed', 'Смешанная'), ('recommended', 'Рекомендованная'), ('review', 'Повторение')], default='mixed', max_length=20, verbose_name='Режим')),
                ('exam_task_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='school.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_sessions', to='school.lesson', verbose_name='Тема')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Сессия практики',
                'verbose_name_plural': 'Сессии практики',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Полученные первичные баллы')),
                ('max_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Максимальные первичные баллы')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('student_answer', models.TextField(blank=True, verbose_name='Ответ ученика')),
                ('is_correct', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False, verbose_name='Пропущено')),
                ('marked_for_review', models.BooleanField(default=False, verbose_name='Отмечено для повторения')),
                ('error_type', models.CharField(blank=True, choices=[('theory', 'Не знаю теорию'), ('misread', 'Неверно понял условие'), ('calculation', 'Ошибка в вычислениях'), ('careless', 'Невнимательность'), ('strategy', 'Неправильная стратегия'), ('formatting', 'Ошибка оформления'), ('random', 'Случайный ответ'), ('unclassified', 'Не классифицирована')], max_length=20, verbose_name='Тип ошибки')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_answers', to='school.question', verbose_name='Задание')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='school.practicesession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Ответ в практике',
                'verbose_name_plural': 'Ответы в практике',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['student', 'started_at'], name='school_prac_student_03679d_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceanswer',
            index=models.Index(fields=['session', 'order'], name='school_prac_session_696729_idx'),
        ),
    ]
