# Generated by Django 6.0.6 on 2026-08-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_practice_bank_and_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
    ]
