# Generated by Django 6.0.6 on 2026-08-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_testresult_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер попытки'),
        ),
        migrations.AddField(
            model_name='homeworksubmission',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
    ]
