# Generated by Django 6.0.6 on 2026-08-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_homeworksubmission_attempt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointattempt',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Ключ идемпотентности'),
        ),
    ]
