# Generated by Django 6.0.6 on 2026-08-07 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_checkpointattempt_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название эфира')),
                ('description', models.TextField(blank=True, verbose_name='О чём эфир')),
                ('scheduled_at', models.DateTimeField(verbose_name='Начало эфира')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, verbose_name='Длительность, мин')),
                ('kinescope_id', models.CharField(blank=True, help_text='ID из кабинета Kinescope. Пусто — плеер не показывается.', max_length=100, verbose_name='ID трансляции Kinescope')),
                ('recording_id', models.CharField(blank=True, help_text='Заполняется после завершения, если запись выкладывается.', max_length=100, verbose_name='ID записи эфира')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('live', 'Идёт эфир'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='scheduled', max_length=10, verbose_name='Статус')),
                ('is_published', models.BooleanField(default=False, verbose_name='Показывать ученикам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='school.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Трансляция',
                'verbose_name_plural': 'Трансляции',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['course', 'scheduled_at'], name='school_cour_course__35f89e_idx')],
            },
        ),
    ]
